### ISSUE TITLE
Clicking the back arrow in the browser doesn't work.

### ISSUE THREAD

**Issue by dylanaraps** [veggiedefender/terminal-waifu#1]
## Description

Clicking the back arrow in the browser doesn't take me back to the main page.

## Steps to reproduce:

1. Generate a waifu.
2. Click the back arrow in the browser.
3. You're still on the completed waifu page.

## Expected behavior:

I'm back to the main page where I can input more colors.

Tested on the latest versions of both Chromium and Firefox.

**Comment by veggiedefender** [comment]
I never even considered the back button when I was testing! It's nice to get a new perspective haha. Anyway, I implemented this by just encoding the entire svg in base64 and redirecting to it. You can save the resulting image and it's also aligned better than the old version. I love your suggestions man!

**Comment by dylanaraps** [comment]
Thanks. :)

I'll take a closer look when I get home, see if I find anything else.
