### ISSUE TITLE
If the input contains a curly brace '{' the input format is changed to json.

### ISSUE THREAD

**Issue by dylanaraps** [veggiedefender/terminal-waifu#2]
## Description

If the input contains an opening curly brace '{' the input format is changed to json. All other braces/etc keep the file format the same.

I only found this since my Xresources file contains comments with fold markers like this `! Colors {{{`.

## Steps to reproduce:

1. Set file format to anything other than json.
2. Type a `{` anywhere in the file.

Note: The closing `}` brace doesn't change the file format, only the opening one.

## Expected behavior:

The file format isn't changed to Xresources.

**Comment by veggiedefender** [comment]
Thank you! Do you think it's enough to just check if the first character is a `{`? I just implemented that and it looks resolved. Can you think of any cases where a non-json will have that as the first character?

By the way, [here's the rest of the autodetection function](https://github.com/veggiedefender/terminal-waifu/blob/7819e56d3de6cf8dc0f83e00a55be3e90db7f080/app.js#L66), it's incredible basic (but works for most cases) and was tacked on as an afterthought but I guess that's no excuse for mediocrity.

**Comment by dylanaraps** [comment]
Yup, it works as expected now. 

Thanks. :)
